### ISSUE TITLE
Syntax is not SCSS-compatible

### ISSUE THREAD

**Issue by pepelsbey** [TrySound/postcss-inline-svg#18]
You can start using PostCSS any time you want on any existing project, even with Sass, @ai once said. Just try it and you’re gonna like it! And then I tried, using `sass` with `postcss` and `autoprefixer`, `inlinesvg` plugins…
```
.pipe(sass().on('error', sass.logError))
.pipe(postcss([
	autoprefixer,
	inlinesvg
]))
```
To Inline SVG:
```
&--twitter {
	background-image:svg-load(../assets/images/twitter.svg, fill:#FFF);
	}
```
And then… oops, it’s not CSS-compatible syntax.
```
Error in plugin 'sass'
Message:
    src/styles/blocks/social.scss
Error: error reading values after (
        on line 39 of src/styles/blocks/social.scss
>> 			background-image:svg-load(../assets/images/twitter.svg, fill:#FFF);
   ----------------------------^
```
So I’m actually forced to use the whole PostCSS ecosystem to be able to just inline SVG. Of course I could make it simpler and compatible:
```
background-image:svg-load('../assets/images/twitter.svg');
```
But in this case I have to put in in single quotes and I can’t use `fill: #FFF` thing which makes it less useful. So I wonder:

- Where are your promises @ai?
- Is it possible to make inline-svg’s syntax CSS-compatible?

**Comment by pepelsbey** [comment]
Of course I tried to reverse it and use `postcss` first but then it just choked:
```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: /Users/pepelsbey/Projects/Веб-стандарты/Сайты/wsd.events/src/styles/screen.scss:1:1: Unknown word
// ------------------------------------------------------------------
^
```

**Comment by ai** [comment]
> Where are your promises @ai?

SCSS compatible is not CSS compatible 😉.  CSS can contains colon (for example, in IE's filters).

But we definitely should fix it.

@TrySound what do you think about `=` instead of `:`?

**Comment by ai** [comment]
@pepelsbey as quick solution, you can use postcss-scss and process postcss-inline-svg before SCSS compiler.

**Comment by ai** [comment]
I suggest this plan:

1. Release 1.4 with `=` and `:` support. But plugin will print a warning on outdated `:`.
2. Post it in Twitter and promote by PostCSS account.
3. After few months release 2.0 without `:` support.

**Comment by TrySound** [comment]
@pepelsbey  There is extended way to define svg and it should work with scss
```css
@svg-load nav url(img/nav.svg) {
    fill: #cfc;
    path:nth-child(2) {
        fill: #ff0;
    }
}
.nav {
    background: svg-inline(nav);
}
```

@ai But I don't like `=` and don't think we should force plugins to be compatble with scss (why we have own parser for it?).

**Comment by ai** [comment]
@TrySound “like” or “don’t” like is not a good maintaining ;). We have a problem and we should do something.

Sass users have no good way to inline images. And it is a big market. Right now we have no useful way (extended syntax is long) to use postcss-inline-svg with Sass, so we loose this big market.

Also, this SCSS bug show other problem: many CSS parsers don’t expect `:` in declaration values. Even if we will ignore SCSS users and loose all of them, we will have a problems with other CSS tools.

**Comment by TrySound** [comment]
We need somebody who will fix all other parsers :)

**Comment by pepelsbey** [comment]
I’d expect something like this, since URL params are well-known to developers:
```
background-image:svg-load('../assets/images/twitter.svg?fill=red&stroke=green')
```

**Comment by ai** [comment]
@pepelsbey URL parameters is not really readable. Spaces is useful :).

```css
background-image: svg-load('../assets/images/twitter.svg', fill=red, stroke=green);
```

**Comment by ai** [comment]
Also it is easy for text editor plugins to highlight colors in this parameters rather than in URL parameters.

**Comment by pepelsbey** [comment]
I’m just trying to avoid PostCSS mess with my syntax highlighter which is set to SCSS.

**Comment by TrySound** [comment]
server may use query string for own goal and using it for styling can broke something.

**Comment by ai** [comment]
@TrySound `svg-load` accepts only file path ;).

But anyway I think `, fill=red, stroke=green` is more readable. And it can’t have any special highlight problems. If text editor highlight custom function, it will highlight params too. Especially in SCSS, when you can define custom function with many parameters.

**Comment by TrySound** [comment]
Oops. Yeah. I'm just working with http :)

**Comment by TrySound** [comment]
@ai customisable separator maybe with a few valid variants `[':', '=', '^']`? I just don't want to see `=` in my code.

**Comment by ai** [comment]
@TrySound yeap, we can add `:` and `=` support and then replace `:` to `=` only in docs.

But why you avoid `=`? You could make this plugin code too complicated with so many syntax option. Remember Stylus lesson, when his parser become unmaintable.

**Comment by TrySound** [comment]
@ai Never used stylus :) It will be hack for sass users, but postcss plugins should use whole power of available syntax.

**Comment by ai** [comment]
@TrySound you talk like fanatic, not like careful maintainer. Maintaining is a responsibility ;).

Why `:` is so better, than `=`? The reason should be big, because supporting two syntax will have bad long-term effects. The one way to do thing is always better.

But if a reasons is important we can support both. It is always question of trade-offs.

**Comment by pepelsbey** [comment]
@TrySound, don’t try to make it _right_ only for PostCSS ecosystem, make it _useful_ for Sass users too.

**Comment by ai** [comment]
BTW, Less can’t parse `:` in value too: [online demo](http://lesscss.org/less-preview/#%7B%22less%22%3A%22.twitter%20%7B%5Cn%20%20%20%20background-image%3A%20svg-load(..%2Fassets%2Fimages%2Ftwitter.svg%2C%20fill%3A%23FFF)%3B%5Cn%7D%22%7D)

**Comment by ben-eb** [comment]
Isn't `:` more CSS-like? `=` only appears in attribute selectors (`[href="blue"]`). We also use `:` in postcss-use, along with an extended, more CSS-like syntax.

https://github.com/postcss/postcss-use#standard-syntax

**Comment by ai** [comment]
@ben-eb all this examples from at-rules or selectors. Not from declaration values. Anyway we just can't use `:` here.

**Comment by ai** [comment]
@TrySound any updates?

**Comment by TrySound** [comment]
Sorry. Didin't have a time yet. Will look this evening.

**Comment by TrySound** [comment]
Fixed https://github.com/TrySound/postcss-inline-svg/commit/946dc2fb62657336013ad060286f6c26effd6dbe

**Comment by pepelsbey** [comment]
@TrySound, thank you! Could you please supply it with usage sample?

@ai and that you too for moral support that looked a bit like a tyranny ;)

**Comment by pepelsbey** [comment]
Nevermind, I see it in the readme. Thank you again!

**Comment by TrySound** [comment]
@pepelsbey I updated docs. You just can use `=` instead of `:`.
