### ISSUE TITLE
Remove fill automatically

### ISSUE THREAD

**Issue by ai** [TrySound/postcss-inline-svg#25]
In Amplifr we have [this problem](https://github.com/TrySound/postcss-inline-svg#why-svg-load-doesnt-work-and-the-color-still-black-or-red-or-whatever). But we can’t use any of your solutions:

1. SVGs are from Evil Icons and we could not change them.
2. CSS is atuogenerated and we could not use `@svg-load` notation.

Maybe we could trim any `fill` attribute on SVG load if user set them?

@TrySound Automatically solution is always better, than FAQ

**Comment by TrySound** [comment]
Released v2.1.0
