### ISSUE TITLE
Color function compatibility 

### ISSUE THREAD

**Issue by mihaeltomic** [TrySound/postcss-inline-svg#28]
Is there a way for a postcss-color-function to work with postcss-inline-svg?

Example:
```
.icon {
    background-image: svg-load(../images/icon.svg, stroke=$color-primary, fill=transparent);
    &:hover {
        background-image: svg-load(../images/icon.svg, stroke=color($color-primary blackness(+10%)), fill=transparent);
     }
}

```

**Comment by TrySound** [comment]
@mihaeltomic Pass inline-svg after color-function and variables in postcss plugin list.

**Comment by mihaeltomic** [comment]
Hey, unfortunately I still have issues after reordering plugins in gulp build. 

![image](https://cloud.githubusercontent.com/assets/7020915/18318555/65be6416-7522-11e6-9055-b9c3e951c29f.png)

![image](https://cloud.githubusercontent.com/assets/7020915/18318564/6efaa4cc-7522-11e6-85cb-f25a1fd8a710.png)


`CSS is: background-image: svg-load(../images/icon--arrow-down.svg, stroke=none, fill=color(black whiteness(+10%)));`

And error is:
`postcss-inline-svg: C:\xampp\htdocs\kbc-osijek\wp-content\themes\kbcosijek\src\css\components.menu.css:128:17: Invalid svg-load() definition`

**Comment by TrySound** [comment]
@mihaeltomic Okay. Remove everything after colorFunction and show me the result.

**Comment by mihaeltomic** [comment]
@TrySound well, if I remove everything the build is not working. 

```
C:\xampp\htdocs\kbc-osijek\wp-content\themes\kbcosijek\gulpfile.js:25
gulp.task('cssBuild', function (){
    ^

SyntaxError: Unexpected token .
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (C:\Users\Mihael\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\Users\Mihael\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\index.js:192:16)

    at module.exports (C:\Users\Mihael\AppData\Roaming\npm\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
```

Can you be more specific, should I remove colorFunction variable in plugins or in gulp.task where I call variables/plugins?

**Comment by TrySound** [comment]
@mihaeltomic I meant drop all plugins after color function. This error in your gulpfile. Skipped parentheses?

**Comment by mihaeltomic** [comment]
Hi, still no luck... Here's gulp file:

`/**
* Require Gulp modules
*/
var gulp = require('gulp'),
    rename = require('gulp-rename'),
    postcss = require('gulp-postcss'),
    plumber = require('gulp-plumber'),
    // PostCSS plugins
    atImport = require('postcss-import'),
    simplevars = require('postcss-simple-vars'),
    colorFunction = require('postcss-color-function'),
    postcssInlineSvg = require('postcss-inline-svg'),
    postcssSvgo = require('postcss-svgo');
gulp.task('cssBuild', function (){
  var postCSSPlugins = [
    atImport ({
      from: 'src/css/app.css'
    }),
    simplevars,
    colorFunction,
    postcssInlineSvg
  ];
  return gulp.src('src/css/app.css')
    // Prevent pipe breaking caused by errors from gulp plugins
    .pipe(plumber({
        errorHandler: function (err) {
            console.log(err);
            this.emit('end');
        }
    }))
    // Add PostCSS plugins to pipe
    .pipe(postcss(postCSSPlugins))
    // Processed folder file destination
    .pipe(gulp.dest('dist/css'))
    .pipe(rename('app.min.css'))
    .pipe(gulp.dest('dist/css'))
});

gulp.task('styles', ['cssBuild'],
    function () {
        gulp.watch('src/css/*.css', ['cssBuild']);
   }
)
`

and here's CSS code:

`$color-test: color(blue blackness(+20%)));

.grid {
    background-image: svg-load(../images/icon--grid-view.svg, stroke=$color-test, fill=transparent);
}
`

**Comment by TrySound** [comment]
There'are two problems.
1. If colorFunction used after simpleVars then plugin looks at "stroke=color" function name and skips it. Solution is placing colorFunction before vars.
2. The second problem is a bug in inline-svg. Color functions including rgb, hsl are not allowed yet in short syntax,

**Comment by ai** [comment]
Spaces will fix a problem? `stroke = color()`?

**Comment by ai** [comment]
We could add warnings to postcss-inline-svg and ask users to use spaces if we see a function in parameter

**Comment by TrySound** [comment]
Yes it can. But it's even uglifer. colon way in this case works very good.

**Comment by ai** [comment]
@TrySound I am not sure, that colon is legal in CSS value :D it is not Sass fail, I think many other CSS tools/parser could not parse `:` in value

**Comment by TrySound** [comment]
Warnings are bad because it can warn even when it doesn't matter. With `rgb` for example. Strict `prop = value` separator sucks.

**Comment by ai** [comment]
If we have a problems only with `postcss-color-function`, we could just fix it. Does `postcss-calc` works with `=`?

**Comment by TrySound** [comment]
@ai The problem that I do not consider `=` as css separator in value-parser and I won't. About calc I'm not sure it's valid in svg props.

**Comment by ai** [comment]
Do we have some good reason to not consider `=` as separator? And why we consider `:` as separator?

**Comment by TrySound** [comment]
@ai https://github.com/TrySound/postcss-value-parser/issues/5

**Comment by ai** [comment]
@TrySound so, what about `=`?

**Comment by TrySound** [comment]
It could be a breaking change. And I don't believe I should parse it and consider as valid. It's not css. Just a hack for preprocessors.

**Comment by ai** [comment]
@TrySound `:` in values is not a CSS too ;).

I asked about syntax spec. Could `=` be in function name according CSS spec?

**Comment by TrySound** [comment]
value-parser is used also for at-rule params. So it's valid. I didn't see `=` in specs. If you'll find something, I will add.

**Comment by ai** [comment]
@TrySound here is a spec, ident-token couldn’t have `=`? https://www.w3.org/TR/css-syntax-3/#ident-token-diagram

**Comment by TrySound** [comment]
@mihaeltomic Bug with `Invalid svg-load() definition is fixed`.
