### ISSUE TITLE
Add options for multiple paths in options.path

### ISSUE THREAD

**Issue by andrewodri** [TrySound/postcss-inline-svg#34]
It would be great if an array of paths could be supplied to `options.path`, similar to how the [node-sass includePaths option](https://github.com/sass/node-sass#includepaths) works.

We would need to type check for Array or String on `opts.path`, and if an Array is found, then loop through in order until a match is/isn't found. (And return an error if there != 1 results found)

Reference: https://github.com/TrySound/postcss-inline-svg/blob/v2.2.0/src/resolveId.js

**Comment by amaschas** [comment]
This would be an incredibly helpful feature. I second this request.

**Comment by Grawl** [comment]
as a workaround I used `path: process.cwd(),` and now I can specify any path in project

so now I can get images from `node_modules`

**Comment by hudochenkov** [comment]
Done in https://github.com/TrySound/postcss-inline-svg/pull/53.
