### ISSUE TITLE
Issue with color-functions

### ISSUE THREAD

**Issue by mihaeltomic** [TrySound/postcss-inline-svg#37]
Again issue with postcss-color-functions and postcss-inline-svg. This one #28 was related but it was fixed.

**Versions:**

```
"devDependencies": {
    "gulp": "^3.9.1",
    "gulp-postcss": "^6.4.0",
    "postcss-color-function": "^3.0.0",
    "postcss-inline-svg": "^2.3.0",
}
```

**Working:**

```
@svg-load nav url(../images/icon.svg) {
    fill: color($color-primary blackness(50%));
}
background: svg-inline(nav);
```
**Dev Tools image:**
![image](https://cloud.githubusercontent.com/assets/7020915/25697529/9b02ff1a-30bb-11e7-819d-2f6b0c7b150a.png)

**Not working:**
`background: svg-load('../images/icon.svg', fill: color($color-primary blackness(50%)));`

**Dev Tools image:**
![image](https://cloud.githubusercontent.com/assets/7020915/25697512/863bfee2-30bb-11e7-84bc-9bd6fa68c800.png)

Any idea?

**Comment by TrySound** [comment]
@mihaeltomic Any warnings in terminal?

**Comment by mihaeltomic** [comment]
@TrySound Yep, sorry for missing that part:

`postcss-inline-svg: D:\PROJECTS\startgator-custom\src\css\base.globals.css:39:5: Invalid svg-load() definition`

**Comment by TrySound** [comment]
@mihaeltomic I checked this example.
```
background: url("data:image/svg+xml;charset=utf-8,<svg id='basic' fill='rgb(128, 128, 128)'/>");
```
Works fine. I guess something wrong with your configuration. Pass you postcss config please

**Comment by TrySound** [comment]
Looks like wrong order again.

**Comment by TrySound** [comment]
Published [v2.3.1](https://github.com/TrySound/postcss-inline-svg/releases/tag/v2.3.1)
Now you can see what parser takes from previous plugin.

**Comment by mihaeltomic** [comment]
@TrySound can you check your example with color-function included?

Here's my postcss config (didn't include all the unnecessary config from gulpfile):
```
// PostCSS build task
gulp.task('cssBuild', function (){
  var postCSSPlugins = [
    // Import CSS file to be built with its imports
    atImport ({
      from: 'src/css/app.css'
    }),
    // Add mixin PostCSS support
    mixins,
    // Add variables PostCSS support
    simplevars,
    // Add nesting PostCSS support
    nested,
    // Add CSS color functions PostCSS support
    colorFunction,
    // Reference an SVG file and control its attributes with CSS
    postcssInlineSvg,
    // Add calc PostCSS support
    calc,
    // Add custom media queries PostCSS support
    customMedia,
    // Add W3C CSS color function to more compatible CSS PostCSS support
    colorFunction,
    // Add vendor prefixing PostCSS support
    autoprefixer ({
      browsers: ['last 2 version']
    })
  ];
  return gulp.src('src/css/app.css')
    // Prevent pipe breaking caused by errors from gulp plugins
    .pipe(plumber({
        errorHandler: function (err) {
            console.log(err);
            this.emit('end');
        }
    }))
    // Add PostCSS plugins to pipe
    .pipe(postcss(postCSSPlugins))
    // Processed folder file destination
    .pipe(gulp.dest('dist/css'))
    // Minify the CSS
    .pipe(postcss([
        cssNano
    ]))
    // Rename
    .pipe(rename('app.min.css'))
    .pipe(gulp.dest('dist/css'))
    .pipe(connect.reload());
});
```

I'll update to 2.3.1

**Comment by mihaeltomic** [comment]
I've updated and now it's working like a charm ;)

**Comment by TrySound** [comment]
@mihaeltomic And again. color function plugin should be before inline-svg

**Comment by mihaeltomic** [comment]
@TrySound ok, but now it's working with this case:

`background: svg-load('../images/icon.svg', fill: color($color-primary a(0.1)));`

**Comment by TrySound** [comment]
Did you try it in browser?

**Comment by mihaeltomic** [comment]
Yes, it's working in both of my projects.

**Comment by TrySound** [comment]
I see you added it twice.

**Comment by mihaeltomic** [comment]
Oh, thanks ;) I had earlier some refactoring, will remove. I consider this to be finished.
