### ISSUE TITLE
Support Promises in `options.encode`

### ISSUE THREAD

**Issue by ivancuric** [TrySound/postcss-inline-svg#41]
I'm currently using a process to transform my SVGs and the SVGO library has recently been updated to be promise-based.

It currently looks like this:
```js
const inlineSvgBuild = async data => {
  const plugins = [...coreSvgoPlugins];
  const optimized = await optimizeSvg(fixSvgDimensions(decodeURI(data)), plugins);
  return encodeURI(optimized);
};
```

And the plugin is invoked as

```js
inlineSvg({ path: paths.src.svg, encode: inlineSvgBuild }),
```

The error recieved is `code.replace is not a function`.

Currently looking at https://github.com/TrySound/postcss-inline-svg/blob/master/src/load.js but no luck. Any ideas?

**Comment by ai** [comment]
@TrySound seems like SVGO 1.0 compatibility problems?

@ivancuric post the full stack trace

**Comment by TrySound** [comment]
I believe encode option is not the right place for svg minification. There is postcss-svgo plugin which optimizes all urls with `data:svg`, not only generated by this plugin.
If you need some features from the new version, please send this issue to [postcss-svgo repository](https://github.com/ben-eb/postcss-svgo).
