### ISSUE TITLE
Is it possible to use webpack resolver with `~/path/to/file`?

### ISSUE THREAD

**Issue by O4epegb** [TrySound/postcss-inline-svg#46]
For example, with `file-loader` I can do `background: url('~svg/icon.svg');` and webpack will resolve the file. 
If I try `background: svg-load('~svg/icon.svg');` it still tries to find the file inside current folder.

**Comment by hudochenkov** [comment]
We're not going to implement complicated resolver. It's kind of out of scope of this package.

In `postcss-inline-svg@4.0.0` we added `paths` option which allow to specify multiple paths to resolve URL. It might be solution you needed.

**Comment by O4epegb** [comment]
I understand that this is just a plugin, not a loader itself, but don't you have access to webpack `resourcePath` field? You don't need to implement resolver at all, webpack handles heavy weight

Anyway, thanks for the answer
