### ISSUE TITLE
Any plan for {removeStroke : true}

### ISSUE THREAD

**Issue by iankit3** [TrySound/postcss-inline-svg#47]

**Comment by hudochenkov** [comment]
I think `removeStroke` kind of makes sense since we can change fill and have `removeFill`. @TrySound what do you think?

**Comment by TrySound** [comment]
I'm ok with this.

**Comment by hudochenkov** [comment]
@iankit3 PR is welcome! You can use `removeFill` option as an example.

**Comment by iankit3** [comment]
Sure on it, will ask for help if needed.

**Comment by hudochenkov** [comment]
Released in `4.1.0`.
