### ISSUE TITLE
IE 11 issues

### ISSUE THREAD

**Issue by morgangraphics** [TrySound/postcss-inline-svg#48]
I recently had an issue where encoded svg images were not showing up in IE 11

My svg's had style declarations (as part of some other upstream export process) where curly braces were included. 

e.g 
```url("data:image/svg+xml;charset=utf-8,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 416.45 315.65' fill='%231AEDCD' stroke='%231AEDCD'%3E%3Cdefs%3E%3Cstyle%3E.a{fill:%231c3353}.b,.c,.d,.e{fill:none}.b{stroke:%231c7686;stroke-width:10.29px}.b,.......```

Current work around: in the .postscssrc file I amended the default encoding to escape the curly braces

```
...
encode: function encode(code) {
  return code
    .replace(/%/g, "%25")
    .replace(/</g, "%3C")
    .replace(/>/g, "%3E")
    .replace(/&/g, "%26")
    .replace(/#/g, "%23")
    .replace(/{/g, '%7B')
    .replace(/}/g, '%7D');
}
...
```

which solved the issue. You may want to include `.replace(/{/g, '%7B')` and `.replace(/}/g, '%7D');` as part of the default encode function.

**Comment by hudochenkov** [comment]
Thanks for the suggestion!
