### ISSUE TITLE
Adds the fill/stroke attribute to <svg> element

### ISSUE THREAD

**Issue by strarsis** [TrySound/postcss-inline-svg#71]
Although it works, the plugin adds the `fill`/`stroke` attributes to the `<svg>` element instead to the child element(s). Would this result in a valid SVG?

**Comment by hudochenkov** [comment]
Yes, `fill` and `stroke` are valid on `<svg>` element. https://developer.mozilla.org/en-US/docs/Web/SVG/Element/svg
